### ISSUE TITLE
Sylius plugins conventions

### ISSUE THREAD

**Issue by Zales0123** [Brille24/SyliusTierpricePlugin#2]
Hello everyone, I would like to congrats you for this awesome plugin, great job! It surly provides really useful functionality for **Sylius** :) I think we would be very proud to show your plugin on [plugins list on our website](https://sylius.com/plugins/), however we have some strict naming conventions defined, which not all of them are fulfilled by this project - take a look at http://docs.sylius.com/en/1.1/plugins/creating-plugin.html#naming-conventions. The most important thing is using `SyliusPluginTrait` and proper extension naming.
Moreover, if you would need/want some code review regarding Sylius coding standards, I'm sure some of us would be pleased to do this :)

Nevertheless, great work, it's good to have such a plugin in **Sylius** ecosystem and such a team in **Sylius** community :)

**Comment by mamazu** [comment]
Thanks for the offer, we will be working on it.

**Comment by mamazu** [comment]
I have refactored the code. However, I was wondering what repository was meant in the section stating 

> Repository name should use dashes as separator, must have a `sylius` prefix and a `plugin` suffix

in the Sylius documentation. Does it refer to the github repository or the composer package?

**Comment by Zales0123** [comment]
It's definitely about composer package (for example `friendsofsylius/sylius-import-export-plugin` for **SyliusImportExportPlugin** etc.). Btw, you can take a look at [SyliusShopApiPlugin](https://github.com/Sylius/SyliusShopApiPlugin) - even though it does not keep all the conventions (it had been done long time before we established them), it's one of the best example how SyliusPlugin should look and work :)

**Comment by mamazu** [comment]
Ok, thanks. I moved the package and will prepare a release soon. Anything I forgot?

**Comment by Zales0123** [comment]
Sorry for the reeeeealy long response time 😄It's fine now, the only thing that could be done yet is setting up Continuous Integration platform. We recommend https://travis-ci.org/, especially, because it's free for open-source project :) You can take a look at [Sylius-Standard](https://github.com/Sylius/Sylius-Standard/blob/master/.travis.yml), to know what you're able to configure there. The same for https://github.com/Brille24/SyliusCustomOptionsPlugin.

This plugin is already on our [Plugin page](https://sylius.com/plugins/), the `CustomOptionsPlugin` will be listed there for sure in the nearest future :)

Thank you! 🎉

**Comment by mamazu** [comment]
Sounds great. I have already created a ticket for this issue. #5
