### ISSUE TITLE
Does it support Sylius 1.3.x

### ISSUE THREAD

**Issue by jcgdjob** [Brille24/SyliusTierpricePlugin#26]
I am on Sylius 1.3.5 and it won't allow me to install (tried also version 0.8).

**Comment by mamazu** [comment]
Thank you for reporting this bug. In version 0.8 it should work as it has the version constraint `1.3`. But I will prepare a release of the version 0.9 which is base on sylius 1.3.x later this day.

**Comment by mamazu** [comment]
Version 0.9 is out.

**Comment by jcgdjob** [comment]
> Version 0.9 is out.

Thanks!

But after installation, I cannot find the "Tier price" on the menu of product variant edit. How could I fix it?

**Comment by mamazu** [comment]
Have you tried to update it? I have made some fixes to it.

**Comment by jcgdjob** [comment]
> Have you tried to update it? I have made some fixes to it.

Just did but still the same... 
I run "php bin/console debug:container | grep tierprice"
and it's showing up.

Since I have updated ProductVariant entity before, I added the oneToMany "tierPrices" on ymal 
And the class extends Brille24\SyliusTierPricePlugin\Entity\ProductVariant
I guess my changes not related to the tab menu not showing up.

Any clues?

**Comment by mamazu** [comment]
Have you included the service definition as defined in the `README.md`?

**Comment by jcgdjob** [comment]
> Have you included the service definition as defined in the `README.md`?

You are right. I have forgot to import 
`- { resource: "@Brille24SyliusTierPricePlugin/Resources/config/services.yml" }`
Thanks!

Another error on js when pressing the add button.
```
Uncaught TypeError: table.find(...).filter(...).sortElements is not a function
    at HTMLTableCellElement.<anonymous> (itemCollectionRender.js:71)
    at Function.each (VM698 jquery-3.3.1.min.js:2)
    at w.fn.init.each (VM698 jquery-3.3.1.min.js:2)
    at tierPriceTableSort (itemCollectionRender.js:65)
    at tierPriceTableAdd (itemCollectionRender.js:10)
    at HTMLDivElement.onclick (edit:530)
```

**Comment by mamazu** [comment]
Glad I could help. :) Thanks for using our plugin.
