### ISSUE TITLE
Tag current master

### ISSUE THREAD

**Issue by magdkudama** [Brille24/SyliusTierpricePlugin#36]
Thanks for the work on this bundle, it's great.

This bundle is currently not allowing usage with Sylius 1.5. Do you see any specific reason why not to tag master, as it has a dependency on Sylius (`^1.4`) that'd allow using v1.5?

Currently we can only use Sylius 1.4, as the latest tag (see https://github.com/Brille24/SyliusTierpricePlugin/blob/v1.4.5/composer.json#L9) does not allow using anything > 1.4.X.

**Comment by mamazu** [comment]
I don't see any reason why it should be a problem. If you want to submit a pull request with a new version constraint, feel free to.

**Comment by magdkudama** [comment]
I don't need to send a PR, in master it's already using the right version. It just needs to be tagged and sent to Packagist.

https://github.com/Brille24/SyliusTierpricePlugin/blob/master/composer.json#L9

I cannot tag the repo, nor send to Packagist.

**Comment by mamazu** [comment]
Ah yeah. I will do that now.

**Comment by mamazu** [comment]
Done. Thanks for letting me know.

**Comment by magdkudama** [comment]
Working fine, thank you
