### ISSUE TITLE
Unable to override plugin templates

### ISSUE THREAD

**Issue by olia-bn** [Brille24/SyliusTierpricePlugin#39]
It seems impossible to override plugin templates using the Symfony's [override bundle resource functionality](https://symfony.com/doc/4.4/bundles/override.html).

This applies to Sylius ThemeBundle as well; neither of structures below work, Symfony Profiler consistently lists rendered template (name & path) as `@Brille24SyliusTierPricePlugin/Resources/views/Shop/Product/Show/_tier_price_promo.html.twig` / `vendor/brille24/sylius-tierprice-plugin/src/Resources/views/Shop/Product/Show/_tier_price_promo.html.twig`, also after clearing cache.

**App:**
```
- templates
    - bundles
        - Brille24SyliusTierPricePlugin
            - Shop
                - Product
                    - Show
                        - _tier_price_promo.html.twig
```

**Theme:**
```
- themes
    - [theme]
        - Brille24SyliusTierPricePlugin
            - views
                - Shop
                    - Product
                        - Show
                            - _tier_price_promo.html.twig
```

**Comment by olia-bn** [comment]
After digging deeper it seems that the resources are not named consistently with Symfony guidelines: the `/Resources/views/` should not be part of the name.

Work-around: different (non-standard) directory structure.

App:
`src/Resources/Brille24SyliusTierPricePlugin/views/Shop/Product/Show/_tier_price_promo.html.twig`

Theme:
`src/themes/[theme]/Brille24SyliusTierPricePlugin/views/Resources/views/Shop/Product/Show/_tier_price_promo.html.twig`

**Comment by mamazu** [comment]
Thanks for bringing this issue up. I haven't had a look at the Symfony 4+ directory structure as the plugin as never used with Themes. So you'd suggest to change the documentation on how to override the templates?

**Comment by olia-bn** [comment]
The only change needed is removing `/Resources/views` from resource names, Symfony's resource Loader then correctly locates any overrides.
