### ISSUE TITLE
Fixtures loading is broken

### ISSUE THREAD

**Issue by jdubuisson** [Brille24/SyliusTierpricePlugin#42]
After upgrading from 1.0 to 1.6, my existing fixtures failed to load.

It seems that the TierPriceExampleFactory is not properly configured to resolve the fixtures data, and turn the given strings (product_variant and channel) into the matching objects.

**Comment by mamazu** [comment]
Yes Sylius has changed the default channel so now it can be that the fixtures need to renamed.
