### ISSUE TITLE
Exception during the database update

### ISSUE THREAD

**Issue by TatianFischer** [Brille24/SyliusTierpricePlugin#54]
Hi,
I try to install your plugin but when I update the database, the console show the exception

In SchemaException.php line 108:
The table with name 'sylius_dev.sylius_product_variant' already exists.

My sylius version is 1.7

**Comment by mamazu** [comment]
Hey,
the error is correct this table should exist. We only override the table. What type of mapping do you use for your project. Currently we only support XML mappings for the `ProductVariant`.

I don't think that Sylius has made a BC break for plugins.

**Comment by TatianFischer** [comment]
Hi,

I use annotation mappings.
Sorry I didn't know TierPriceProduct only support XML mappings

Thank for the answer

**Comment by mamazu** [comment]
I should add that to the documentation. Good point. Thanks for reporting that.

**Comment by mamazu** [comment]
Fixed in: b30306a
