### ISSUE TITLE
Plugin installation override the doctrine migration_paths order

### ISSUE THREAD

**Issue by kevinbalicot** [Brille24/SyliusTierpricePlugin#63]
Sylius version : 1.9
Plugin version : v2.0.1

After installing the plugin, I noticed that all the migrations that we create using the doctrine:migrations:diff (or :generate) ends up in the plugins migration folder, instead of the project's directory.

Turns out the plugin's Brille24SyliusTierPriceExtension class prepend its migration_path, causing the following thing :
![image](https://user-images.githubusercontent.com/4362142/122559205-54411300-d03f-11eb-93d6-0216dca8ac83.png)

Migrations are correctly setup in our project (see our config/packages/doctrine_migrations.yaml file)
image

![image](https://user-images.githubusercontent.com/4362142/122559238-602cd500-d03f-11eb-8aa6-d81709a5019e.png)

Maybe you can follow this patch from  [BitBagCommerce/SyliusWishlistPlugin](https://github.com/BitBagCommerce/SyliusWishlistPlugin/pull/52)

Thanks

**Comment by mamazu** [comment]
Thanks for you bug report we have been running into the same issues. We will have a look into the fix provided by Bitbag.

**Comment by mamazu** [comment]
This is fixed in the master branch. Would you be so kind and try out if this actually solves the problem?

**Comment by kevinbalicot** [comment]
It's work fine :D Thanks you
