### ISSUE TITLE
sylius 1.11 support

### ISSUE THREAD

**Issue by tuxes3** [Brille24/SyliusTierpricePlugin#66]
https://github.com/Brille24/SyliusTierpricePlugin/pull/65

**Comment by Roshyo** [comment]
This can be closed then :smile:

**Comment by mamazu** [comment]
Theoretically, true. I'll still need to fix the pipeline. That's why it's still open.

**Comment by mamazu** [comment]
Well it looks like the sylius time package is missing for the 1.11 release. Is that correct?
https://github.com/Brille24/SyliusTierpricePlugin/runs/5886545300?check_suite_focus=true
on this branch
https://github.com/Brille24/SyliusTierpricePlugin/tree/fixing_master
