### ISSUE TITLE
Support for Sylius 1.12

### ISSUE THREAD

**Issue by olia-bn** [Brille24/SyliusTierpricePlugin#68]
Any chance for compatibility with Sylius 1.12?

**Comment by mamazu** [comment]
Hey, thanks for using this plugin. We are planning on adding 1.12 support in the future. However you should be able to use it with 1.12 as well, if you change the requirements in the `composer.json` file.

If you want to test it with 1.12 and make it work, a pull request would be more than welcome.

**Comment by t-n-y** [comment]
Hi 
any update on when the plugin will be compatible with sylius 1.12 ? 
Thanks

**Comment by mamazu** [comment]
Thanks for poking me again. Working on it now. #70

**Comment by mamazu** [comment]
Can someone check out release: 2.3.0-ALPHA of this plugin if it works. I can't seem to get the test application working.

**Comment by t-n-y** [comment]
@mamazu i ll install and try it. i ll let you know

**Comment by mamazu** [comment]
@t-n-y Thanks for testing. Can you use this for now. I want to do some code refactoring since it's probably going to include BC breaks anyways. But I will keep you updated.

**Comment by t-n-y** [comment]
@mamazu sure, no pb

**Comment by cwa-cc** [comment]
Hi,
I'm trying to install the plugin for Sylius 1.12.5 
Is the installation documentation up to date ?

**Comment by mamazu** [comment]
Yes, the installation instruction should be the same as the previous version.s

**Comment by mamazu** [comment]
@t-n-y Could you test the master branch again. If you say it's good, then I'll tag a new version.

**Comment by t-n-y** [comment]
@mamazu i tried on master, but can't find "@Brille24SyliusTierPricePlugin/Resources/config/resources.yml".

is the readme not updated or the file is really missing ?

**Comment by mamazu** [comment]
Thanks for pointing that out, I have removed the config file from the documentation. I have merged the `config.yaml` and `resource.yaml` into one thing.

**Comment by t-n-y** [comment]
@mamazu looks good to me

**Comment by mamazu** [comment]
Tagged it as a new release v2.3.0

**Comment by cwa-cc** [comment]
Hi

I come back to you, because, since I've installed the plugin, I have migrations problem.

When I make `doctrine:migrations:diff` for example, it always have this error :
`The table with name 'xxx.sylius_product_variant' already exists.` 

Maybe I do something wrong or I forgot to do something

Have an idea to fix it ?

Thanks in advance

**Comment by t-n-y** [comment]
yes , thanks

**Comment by mamazu** [comment]
Can we close the issue for now?
