### ISSUE TITLE
Missing file Brille24SyliusTierPriceBundle

### ISSUE THREAD

**Issue by wimulkeman** [Brille24/SyliusTierpricePlugin#7]
After adding the bundle using composer, I added the following part to AppKernel following the README.
```php
public function registerBundles()
{
    return array_merge(parent::registerBundles(), [
        ...

        new \Brille24\SyliusTierPricePlugin\Brille24SyliusTierPriceBundle(),
    ]);
}
````
This file is missing in the bundle. I would aspect it to be at vendors/brille24/sylius-tierprice-plugin/Brille24SyliusTierPriceBundle.php.

Does the part in the AppKernel need to point to another file, or is the file missing?

**Comment by mamazu** [comment]
Fixed the `README.md` typo. The class should be `Brille24SyliusTierPricePlugin`. Please try again now.

**Comment by wimulkeman** [comment]
Thanks it resolved the issue.
