### ISSUE TITLE
I cannot see "tier prices" in a configurable product 

### ISSUE THREAD

**Issue by Dragnucs** [Brille24/SyliusTierpricePlugin#72]
I have an instance of Sylius v1.11 standard edition runnning where I installed Tier Price plugin following instructions on the readme. However, I cannot see the menu entry For Tier prices as shown in the instructions screenshot.

The deviation I was forced to take from the instruction is that I manually merged the contents of Resources/config/config.yml inside of config/package/_sylius.yaml and also updated src/Entity/Product/ProductVartiant.php to extend from you plugin rather than from Sylius Core.

Please notice that the menu entry and form do show up for simple products. Yet I need configurable products.

Is Standard Edition simply not supported or am I missing something?

Thanks in advance.

**Comment by mamazu** [comment]
Hey, we have never tested this plugin to work with configurable products. But it should work. The thing is that the tierprices tab will not be on the product page but it would be on the variant page. Did you check that?

**Comment by Dragnucs** [comment]
I look both in product page and variant page. By the way, it is necessary for it to be in variant page as this is what has the actual product and price.

Maybe if there is some template or something I need to override myself for it to work. Just some guidance to cut through exploration time.

**Comment by mamazu** [comment]
Well, I found the issue. It was a problem with the code. I have deployed a fix with the latest version. Can you try it updating to version 2.3.1?

**Comment by Dragnucs** [comment]
My apologies for the late response. I finally got around updating the package. I cant indeed see the tab in product variant for configurable products. However, due to my setup, I am struggling a bit with JS assets, and cannot confirm if the fully works. Any ways, original issue is resolved. I am diving more into my assets problem and will let you know.

Thank you very much.
