### ISSUE TITLE
Dependency injection fails: non-existent service brille24.factory.tierprice

### ISSUE THREAD

**Issue by olia-bn** [Brille24/SyliusTierpricePlugin#76]
Container fails to compile if I import resource `'@Brille24SyliusTierPricePlugin/Resources/config/config.yml'` via `config/config.yaml` (so: following Readme instructions).

```
The service "Brille24\SyliusTierPricePlugin\Factory\TierPriceFactoryInterface" has a dependency on a non-existent service "brille24.factory.tierprice".
```

But it will compile if I include / replace relevant lines in `_sylius.yaml` config file.

Main packages are
```
    "require": {
        "php": "^8.2",
        "ext-json": "*",
        "brille24/sylius-tierprice-plugin": "2.3.2",
        "sylius/invoicing-plugin": "^0.24.0",
        "sylius/paypal-plugin": "^1.5.1",
        "sylius/refund-plugin": "^1.4",
        "sylius/sylius": "1.12.12",
        "symfony/dotenv": "^6.3.7",
        "symfony/flex": "^2.4.1",
        "symfony/runtime": "^6.3.2"
    },
```

Update: while container complies if I make changes / additions to sylius resources in `_sylius.yaml` file, attempting to update doctrine schema ill fail with `The table with name "alka_webshop.sylius_product_variant" already exists.`

It will work if I update `ProductVariant` definitions in App bundle with SyliusTierPrice bundle relevant changes.

**Comment by olia-bn** [comment]
> If you already have overwritten the ProductVariantEntity then you want to extend your implementation with the traits provided in the package

This must be the issue. Stock Sylius installation seems to override all of them by default, so it didn't click in my head, especially since I set up the test env months ago. Maybe it's worth pointing it out for other devs that might not realise this is what happens by default?

> There are also some known problems with projects that don't use XML for configuring their entities.

I use annotations indeed. So this might be the case. Any particular git issue you know of that I can look at for more info?

**Comment by mamazu** [comment]
Yeah you are completely right, we should add this information to the docs. When I saw Sylius change that behavior ages ago, I ran into the same issue myself. :D

As for your mapping issue, sadly no. If you have time to add attributes to the class to make it extendable that would be great, but other than that I'm not sure there is an open issue for this yet.
