### ISSUE TITLE
Sylius resource should not be overridden in plugin

### ISSUE THREAD

**Issue by Roshyo** [Brille24/SyliusTierpricePlugin#86]
Inside `/src/Resources/config/config.yml` there is a redeclaration of a Sylius resource (product variant)

A plugin should never do that but instead propose a trait (which is there) and do that override inside the `tests/Application/src` folder to try it when developping.

If a plugin overrides that definition, it's loaded after `_sylius.yaml` in native install, and then the Entity definition takes over the project's definition.

**Comment by mamazu** [comment]
Thanks for bringing this up. Can you check if the attached PR would fix this? Then I'll release a new version without the override. (New major version unfortunately as this is a technically a bc break).

**Comment by Roshyo** [comment]
Looks like it fixes it yes. But you should probably add those lines back into tests/Application for the test environment (or local when developing) to work
