### ISSUE TITLE
No support of Sylius1.13.*

### ISSUE THREAD

**Issue by tig3ro** [Brille24/SyliusTierpricePlugin#90]
Hello there.

Do you plan to add support for Sylius1.13.*?

regards,
Tig3ro

**Comment by mamazu** [comment]
Hey, in general this plugin should work with Sylius 1.13. At least I don't know any BC breaks. Would you be able to check it with 1.13 then I will just update the `composer.json`

**Comment by mamazu** [comment]
The plugin now supports all 1.x versions if you could try and give feedback that would be nice.

**Comment by tig3ro** [comment]
I confirm it works like a charm with Sylius 1.13.4. Thank you very much!
